name: "Recovery partition boot setup"
stages:
   boot:
     - name: "Recovery"
       if: '[ -f "/run/cos/recovery_mode" ]'
       commands:
       - |
            source /etc/os-release
            echo >> /etc/issue
            echo "You are booting from recovery mode. Run 'elemental reset' to reset the system to $VERSION" >> /etc/issue
            echo " or 'elemental upgrade' to upgrade the active partition" >> /etc/issue
            echo >> /etc/issue
