name: "LiveCD Detection"
stages:
   rootfs.before:
     - if: |
            cat /proc/cmdline | grep -q "CDLABEL" || cat /proc/cmdline | grep -q "elemental.disable"  || cat /proc/cmdline | grep -q "rd.cos.disable"
       name: "Identify live mode"
       files:
       - path: /run/elemental/live_mode
         content: "1"
         permissions: 0600
         owner: 0
         group: 0
       - path: /run/cos/live_mode
         content: "1"
         permissions: 0600
         owner: 0
         group: 0
     - if: '[ -f "/run/cos/live_mode" ]'
       name: "Include cloud init files from the ISO root"
       files:
       - path: /etc/cos/config.d/iso-cloud-init-paths.yaml
         content: |
                  cloud-init-paths:
                    - "/run/initramfs/live/iso-oem"
         permissions: 0644
         owner: 0
         group: 0
