name: "Root autologin"
stages:
  initramfs.after:
  - if: '[ -f /run/elemental/live_mode ]'
    files:
    - path: /etc/systemd/system/serial-getty@ttyS0.service.d/override.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=-/sbin/agetty --autologin root --noclear %I $TERM
      permissions: 0644
    - path: /etc/systemd/system/getty@tty1.service.d/override.conf
      content: |
        [Service]
        ExecStart=
        ExecStart=-/sbin/agetty --autologin root --noclear %I $TERM
      permissions: 0644
