name: "Start installer on tty1"
stages:
  initramfs:
  - if: |
      [ -f /run/cos/live_mode ] && \
      ( [ -e "/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ] || [ -e "/usr/sbin/systemctl" ] || [ -e "/usr/bin/systemctl" ] )
    commands:
    - systemctl disable getty@tty1
    - systemctl stop getty@tty1
    - systemctl mask getty@tty1
    - systemctl enable llmos-install
