version: 1

env:
  - LLMOS_CLI_REPO={{ if index .Env "LLMOS_CLI_REPO"  }}{{ .Env.LLMOS_CLI_REPO }}{{ else }}docker.io/oneblockai/llmos-cli{{ end }}
  - BUILDER={{ if index .Env "BUILDER"  }}{{ .Env.BUILDER }}{{ else }}default{{ end }}
  - VERSION={{ if index .Env "VERSION"  }}{{ .Env.VERSION }}{{ else }} {{ .Version}} {{ end }}

snapshot:
  # https://goreleaser.com/customization/snapshots/
  name_template: '{{ trimprefix .Summary "v" }}'

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: 'checksums.txt'

builds:
  - id: "llmos"
    binary: llmos
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    tags:
      - netgo
    ldflags:
      - -s
      - -w
      - -X "github.com/oneblock-ai/llmos/cmd/version.Version={{ .Env.VERSION }}"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
    - "^docs:"
    - "^test:"

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: package/Dockerfile.cli
    image_templates:
      - "{{ .Env.LLMOS_CLI_REPO }}:{{ .Env.VERSION }}-amd64"
    build_flag_templates:
      - "--builder={{ .Env.BUILDER }}"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Env.VERSION}}"
      - "--label=org.opencontainers.image.source=https://github.com/oneblock-ai/llmos"
      - "--platform=linux/amd64"

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: package/Dockerfile.cli
    image_templates:
      - "{{ .Env.LLMOS_CLI_REPO }}:{{ .Env.VERSION }}-arm64"
    build_flag_templates:
      - "--builder={{ .Env.BUILDER }}"
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Env.VERSION}}"
      - "--label=org.opencontainers.image.source=https://github.com/oneblock-ai/oneblock"
      - "--platform=linux/arm64"

docker_manifests:
  - use: docker
    name_template: "{{ .Env.LLMOS_CLI_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - "{{ .Env.LLMOS_CLI_REPO }}:{{ .Env.VERSION }}-amd64"
      - "{{ .Env.LLMOS_CLI_REPO }}:{{ .Env.VERSION }}-arm64"

docker_signs:
  - artifacts: all
    stdin: "{{ .Env.COSIGN_PASSWORD }}"
