if: '[ ! -f "/run/elemental/recovery_mode" ]'
name: "Rootfs Layout overwrite"
environment_file: /run/elemental/mount-layout.env
environment:
  VOLUMES: "LABEL=COS_OEM:/oem LABEL=COS_PERSISTENT:/usr/local{{ if .HasDataPartition }} LABEL=LLMOS_DATA_PERSISTENT:/mnt/llmos{{ end }}"
  OVERLAY: "tmpfs:25%"
  RW_PATHS: "/var /etc /srv"
  PERSISTENT_STATE_PATHS: >-
    /etc/init.d
    /etc/kubernetes
    /etc/modprobe.d
    /etc/systemd
    /etc/llmos
    /etc/rancher
    /etc/ssh
    /etc/ssl/certs
    /etc/iscsi
    /etc/ceph
    /etc/cni
    /etc/sysconfig
    /etc/systemd
    /etc/elemental
    /home
    /opt
    /root
    /usr/libexec
    /usr/local
    /usr/share/pki/trust
    /usr/share/pki/trust/anchors
    /var/lib/ca-certificates
    /var/lib/calico
    /var/lib/cni
    /var/lib/containerd
    /var/lib/dbus
    /var/lib/extensions
    /var/lib/juicefs
    /var/lib/kubelet
    /var/lib/NetworkManager
    /var/lib/llmos
    /var/lib/rancher
    /var/lib/rook
    /var/lib/selinux
    /var/log
    /mnt
    {{- if .OS.PersistentStatePaths }}
    {{- range $path := .OS.PersistentStatePaths }}
    {{ $path }}
    {{- end }}
    {{- end }}
  PERSISTENT_STATE_BIND: "true"
