---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmos-repo
  namespace: llmos-system
spec:
  selector:
    matchLabels:
      app: llmos-repo
  replicas: 1
  template:
    metadata:
      labels:
        app: llmos-repo
    spec:
      containers:
      - name: repo
        image: ghcr.io/llmos-ai/llmos-repo:main
        ports:
        - name: httpd
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: llmos-repo
  namespace: llmos-system
spec:
  selector:
    app: llmos-repo
  ports:
    - protocol: TCP
      port: 80
      targetPort: httpd
