---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: llmos-operator
  namespace: kube-system
spec:
  repo: http://llmos-repo.llmos-system/charts
  chart: llmos-operator
  targetNamespace: llmos-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: llmos-crd
  namespace: kube-system
spec:
  repo: http://llmos-repo.llmos-system/charts
  chart: llmos-crd
  targetNamespace: llmos-system