apiVersion: v1
kind: Service
metadata:
   name: ollama-service
   namespace: llmos
spec:
   clusterIP: None
   ports:
   - protocol: TCP
     port: 11434
     targetPort: 11434
   type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: ollama-service
  namespace: llmos
subsets:
  - addresses:
    - ip: 10.42.0.1
    ports:
      - port: 11434
